/controller_manager:
  ros__parameters:
    update_rate: 100  # Hzwoj

    cart_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

cart_controllers:
  ros__parameters:
    joints:
      - slider_to_cart
      - x_to_y
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort